#!/usr/bin/env bash
# Refresh requirements/snapshots from each repo's remote branch (not your working tree, which may be on a
# feature branch). Read-only against the repos: it only runs `git fetch` and `git show`.
#
#   WORKSPACE=~/Venxr ./scripts/sync-requirements.sh
set -euo pipefail
WORKSPACE="${WORKSPACE:-$HOME/Venxr}"
OUT="$(cd "$(dirname "$0")/.." && pwd)/requirements/snapshots"
BRANCH="${BRANCH:-venxr_v2}"

# repo|file1 file2 ...   (output dir is the repo name without the venxr_backend- prefix)
SPECS=(
  "venxr_backend-llm_service|requirements.txt requirements_test.txt"
  "venxr_backend-authentication_service|requirements.txt"
  "venxr_backend-utility-service|requirements.txt"
  "venxr_backend-gateway_service|requirements.txt"
  "venxr_backend-whatsapp_webhook_service|requirements.txt"
  "venxr_backend-meta_mcp_service|requirements.txt"
  "venxr_backend-google_ads_mcp_service|requirements.txt"
  "venxr_backend-dv360_mcp_service|requirements.txt"
  "venxr_backend-amazon_ads_mcp_service|requirements.txt"
  "venxr_backend-meesho_seller_mcp_service|requirements.txt"
  "tv_planner_mcp_service|requirements.txt"
  "skill_service|requirements.txt"
  "shared_components|packages/jobqueue/requirements.txt packages/jobqueue/pyproject.toml packages/mailservice/requirements.txt packages/mailservice/pyproject.toml"
  "frontend|package.json"
)

: > "$OUT/SOURCES.md.tmp"
for spec in "${SPECS[@]}"; do
  repo="${spec%%|*}"; files="${spec#*|}"; dir="$WORKSPACE/$repo"
  [ -d "$dir/.git" ] || { echo "skip (not found): $repo" >&2; continue; }
  git -C "$dir" fetch -q origin "$BRANCH"
  sha="$(git -C "$dir" rev-parse --short "origin/$BRANCH")"
  for f in $files; do
    dest="$OUT/${repo#venxr_backend-}/$(echo "$f" | tr '/' '_')"
    mkdir -p "$(dirname "$dest")"
    git -C "$dir" show "origin/$BRANCH:$f" > "$dest"
    echo "| $repo | $f | $BRANCH | $sha |" >> "$OUT/SOURCES.md.tmp"
  done
done
{ echo "# Snapshot sources"; echo; echo "Generated by scripts/sync-requirements.sh on $(date -u +%Y-%m-%d)."; echo
  echo "| Repo | File | Branch | Commit |"; echo "|---|---|---|---|"; cat "$OUT/SOURCES.md.tmp"; } > "$OUT/SOURCES.md"
rm "$OUT/SOURCES.md.tmp"
echo "done. Sandbox pins are inline in its Dockerfiles; edit snapshots/sandbox/inline-pins.txt by hand."
echo "Next: python scripts/pin_report.py"
